services:
  db:
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-indoor}
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER is required}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER is required}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
      PYTHON_ML_DEVICE: "${PYTHON_ML_DEVICE:-cuda}"
    volumes:
      - app-storage:/data/storage

volumes:
  db-data:
  app-storage:
